### ISSUE TITLE
Internal Developer Platform on AWS

### ISSUE THREAD

**Issue by d4nyll** [InternalDeveloperPlatform/public-site#102]
I published a course on Manning titled [Internal Developer Platform on AWS](https://www.manning.com/liveprojectseries/internal-developer-platform-ser) last year. I am wondering whether it would be acceptable to add it to the site or is it too self-promotion-y?

**Comment by christophcrichter** [comment]
@FL303 what do you think?

**Comment by FL303** [comment]
@d4nyll Feel free to add here: https://internaldeveloperplatform.org/articles/
