### ISSUE TITLE
shipa links are broken

### ISSUE THREAD

**Issue by brucellino** [InternalDeveloperPlatform/public-site#116]
Hello 👋🏽

I've noticed that the links in the [shipa page](https://internaldeveloperplatform.org/kubernetes-control-planes/shipa/) are broken. In particular shipa.io redirects to https://shipa.io/cgi-sys/suspendedpage.cgi which shows 
![image](https://github.com/InternalDeveloperPlatform/public-site/assets/2115428/c3631849-5476-4b70-8351-00b33620be69)

**Comment by christophcrichter** [comment]
Hi @brucellino,
shipa.io seems to work again. The docs link is also broken on the shipa page itself.

**Comment by brucellino** [comment]
Thanks @christophcrichter - I guess we can close this, at least the link to the Shipa website from the pages in this repo are working :)
