### ISSUE TITLE
5 core concepts and observability

### ISSUE THREAD

**Issue by sm-moore** [InternalDeveloperPlatform/public-site#162]
This came up for debate today. My team is looking to build an IDP and we are looking at the [5 core components](https://internaldeveloperplatform.org/core-components/). It appears observability/monitoring/alerting is not part of the 5 core concepts but I do see it mentioned other places on the site. What are your thoughts, does an observability platform fit inside of an IDP or is it it's own thing?

Thanks!

**Comment by FL303** [comment]
Thanks for raising this, @sm-moore. Oberservablilty and monitoring definitely fit into an IDP, this is currently in discussion on how to restructure the core components. In the meantime, I would encourage you to hop over to platformengineering.org where you even find some Google slides to draw your own reference architecture of an IDP:
https://platformengineering.org/platform-tooling
https://docs.google.com/presentation/d/1yAf_FSjiA0bAFukgu5p1DRMvvGGE1fF4KhvZbb7gn2I/edit#slide=id.g2a0a50cf76a_0_527

Hope this is helpful!

**Comment by sm-moore** [comment]
Thank you so much!
