### ISSUE TITLE
Selefra link broken

### ISSUE THREAD

**Issue by krumware** [InternalDeveloperPlatform/public-site#170]
https://internaldeveloperplatform.org/security/selefra/ links to a website with a missing deployment and broken certificate.

This is the open-source project page: https://github.com/selefra/selefra

(I can submit a PR but wasn't certain about the project's status. Primary contributor did make a similar update on another repo: https://github.com/tvvocold/FOSS-for-Dev/commit/12ad4bb3c7be5d47dff97f27b2f01f04516584d7)

**Comment by christophcrichter** [comment]
Thanks for the heads-up, @krumware. I just fixed this with a PR.

**Comment by krumware** [comment]
Thanks!
