### ISSUE TITLE
Add Atlassian Compass to buy section

### ISSUE THREAD

**Issue by setchy** [InternalDeveloperPlatform/public-site#53]
[Atlassian Compass](https://developer.atlassian.com/cloud/compass/), still in alpha, is an emerging service offering from Atlassian to provide a developer platform.

**Comment by jkinmonth** [comment]
Thanks for the callout @setchy. We're planning to open a PR shortly.

**Comment by setchy** [comment]
Closing as there is now a page for https://internaldeveloperplatform.org/developer-portals/atlassian-compass/
